[project]
name = "70-days-70-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastai>=2.8.7",
    "fastapi>=0.135.2",
    "nltk>=3.9.4",
    "numpy>=2.4.4",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
    "ultralytics>=8.4.31",
    "wfdb>=4.3.1",
]
